Title: IBM Content Platform Engine (CPE)  5.2.x /IBM VMM(Virtual Member Manager) provider and use of UPN(UserPrincipalName) login attribute. - United States

Text:
IBM; FileNet; CPE; UPN; VMM TECHNOTE (TROUBLESHOOTING)

PROBLEM(ABSTRACT)
 CPE IBM VMM Provider with use of the UPN attribute as your login attribute. The following error will be produced :
--
com.filenet.api.exception.EngineRuntimeException: FNRCE0051E: E_OBJECT_NOT_FOUND: The requested item was not found. Principal icn@p8.com not found.
--
If UPN arttribtue within the LDAP repository meets the following conditions:
==
- UPN attribute does not match mail attribute , e.g. UPN=user1@abc.com ; mail=user1@accounting .abc.com. 

- mail does NOT exist in LDAP repository 

In these conditions map the VMM virtual mail attribute to the actual LDAP user attribute UPN. The use of "mail" virtual property is by design . 

CAUSE
Identified as a product defect under APAR PJ43608

ENVIRONMENT
- Content Engine 5.2.x using the IBM VMM Provider type.
- WebSphere 8.5.5.x ND (Network Deployment)
- Federated Repository configured for MSAD (Microsoft Active Directory) with UPN as login attribute.


Note: This VMM remapping may be required for other Directory providers where potentially mail or email attributes are being used .


DIAGNOSING THE PROBLEM
 

 1. Enable Content Engine tracing for the following subsystems:
    
    
    EJB , Error and Security
    
    
 2. Reproduce issue with UPN login to any CPE based application , e.g. ACCE or client based application ICN ,WPXT ,etc...
    
    
 3. Review newly created "p8_server_trace.log" for the following entries :


== Example, below where UPN =icn@p8.com: 

---
2015-06-19T13:04:19.620 D47E1276 SEC FNRCE0000D - DEBUG Start retrieving user access token by user name [icn@p8.com] from Domain [{00000000-0000-0000-0000-000000000000}]
2015-06-19T13:04:19.622 D47E1276 SEC FNRCE0000D - DEBUG Calling VMMProvider.getUserByUPN(icn@p8.com); SearchProperties: MemberOfGroups, ShortName, Id
2015-06-19T13:04:19.622 D47E1276 SEC FNRCE0000D - DEBUG [look up user by email] data passed to VMM: \n<?xml version="1.0" encoding="UTF-8"?>\n<sdo:datagraph xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n xmlns:sdo="commonj.sdo" xmlns:wim="http://www.ibm.com/websphere/wim">\n <wim:Root>\n <wim:controls xsi:type="wim:SearchControl" expression="@xsi:type='PersonAccount' and mail='icn@p8.com'"/>\n </wim:Root>\n</sdo:datagraph>\n
2015-06-19T13:04:20.181 D47E1276 SEC FNRCE0000D - DEBUG [look up user by email] data returned from VMM: \n<?xml version="1.0" encoding="UTF-8"?>\n<sdo:datagraph xmlns:sdo="commonj.sdo"\n xmlns:wim="http://www.ibm.com/websphere/wim">\n <wim:Root/>\n</sdo:datagraph>\n
2015-06-19T13:04:20.181 D47E1276 SEC FNRCE0000D - DEBUG Called VMMProvider.getUserByUPN(icn@p8.com); Returned: <Empty> 
2015-06-19T13:04:20.181 D47E1276 SEC FNRCE0000D - DEBUG End retrieving user access token by user name [%s] from Domain [%s]
2015-06-19T13:04:20.318 D47E1276 ERR FNRCE0051D - DEBUG com.filenet.api.exception.EngineRuntimeException: FNRCE0051E: E_OBJECT_NOT_FOUND: The requested item was not found. Principal icn@p8.com not found.\n at com.filenet.engine.security.SecurityProvider.getSecurityToken(SecurityProvider.java:618)\n at
---
- Begin search of log for the following entry "com.filenet.api.exception.EngineRuntimeException: FNRCE0051E: E_OBJECT_NOT_FOUND"

- Moving up in stack on the same thread looking for the beginning /start of the VMM provider code 
"VMMProvider.getUserByUPN(icn@p8.com)" call .

- Follow the thread for the VMM search "Calling VMMProvider.getUserByUPN(icn@p8.com) and associated data passed to VMM, specifically the "look up user by email] data passed to VMM:"
---
VMMProvider.getUserByUPN(icn@p8.com); SearchProperties: MemberOfGroups, ShortName, Id
2015-06-19T13:04:19.622 D47E1276 SEC FNRCE0000D - DEBUG [look up user by email] data passed to VMM: \n<?xml version="1.0" encoding="UTF-8"?>\n<sdo:datagraph xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n xmlns:sdo="commonj.sdo" xmlns:wim="http://www.ibm.com/websphere/wim">\n <wim:Root>\n <wim:controls xsi:type="wim:SearchControl" expression="@xsi:type='PersonAccount' and mail='icn@p8.com'"/>\n </wim:Root>\n</sdo:datagraph>\n
--
- See how the VMM Search control expression builds the "SearchControl" expression="@xsi:type='PersonAccount' and mail='icn@p8.com" 

- Evidence that during the actual VMM provider code "VMMProvider.getUserByUPN" lookup is actually calling the "mail" attribute , hence the remapping requirement to make the use of the UPN attribute work.


 


RESOLVING THE PROBLEM
 

(WebSphere Federated Repositories only) 



 1. Search the WebSphere application server profile for wimconfig.xml. 
    
    
    <profile_root>/config/cells/<cell>/wim/config/wimconfig.xml 
    
    
 2. Edit wimconfig.xml in the following way: Remapping required of the current "wimconfig,xml"
    and the current propertyName entries. 
    
    
 3. Make the following changes to the entries within the "winconfig.xml":
    
    <config:attributes name="userPrincipalName" propertyName="uid">
    <config:entityTypes>PersonAccount</config:entityTypes>
    </config:attributes>
    <config:attributes name="userPrincipalName" propertyName="mail">
    <config:entityTypes>PersonAccount</config:entityTypes>
    </config:attributes>
    
    * In the above example the two VMM attributes "uid" and "mail " are mapped. The name attribute
    (userPrincipalName) represents the LDAP attribute type , while the "propertyName" values (uid ;
    mail) represents the VMM virtual attribute. 
    
    
 4. Save wimconfig.xml. 
    
    
 5. Restart the WAS Profile instance , e.g. DMGR 
    
    
    Note: If the property is known to VMM by default (the list of attributes VMM uses by default depends on the repository type) and the property is referenced by its actual name e.g. cn , then there is no need to map the property to another name in VMM. 
    
    For example, if IBM Directory Server is used do not create a mapping for uid in VMM unless the uid is used under a different name. This means that uid does not need to be mapped "to itself", however, it is not an error to do so.