Title: IBM Users unable to login to Connections due to java.sql.SQLException: ORA-00257: archiver error - United States

Text:
Connections user; failed to login; Oracle; ORA-00257; DSRA0010E; 257; Unable to access the required data TECHNOTE (TROUBLESHOOTING)

PROBLEM
Users unable to login to Connections.

SYMPTOM
Excerpted from systemout.log: 

[1/4/17 3:04:12:616 SGT] 000007d4 LotusConnecti E An unexpected
exception was caught by IBM Connections. The error page generated for
this exception will display the identifier below.
[1/4/17 3:04:12:616 SGT] 000007d4 LotusConnecti E Request URI: GET
https:// community.acme.com/profiles/nav/templates/error.jsp
[1/4/17 3:04:12:617 SGT] 000007d4 LotusConnecti E Unable to access
the required data

org.springframework.dao.ConcurrencyFailureException: SqlMapClient
operation; SQL [];
--- The error occurred while applying a parameter map.
--- Check the Login.getProfileByLoginMinimal-InlineParameterMap.
--- Check the statement (query failed).
--- Cause: java.sql.SQLException: ORA-04021: timeout occurred while
waiting to lock object
; nested exception is
com.ibatis.common.jdbc.exception.NestedSQLException:
--- The error occurred while applying a parameter map.
--- Check the Login.getProfileByLoginMinimal-InlineParameterMap.
--- Check the statement (query failed).
--- Cause: java.sql.SQLException: ORA-04021: timeout occurred while
waiting to lock object

at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:109)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
...
at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905)
at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1691)
Caused by: com.ibatis.common.jdbc.exception.NestedSQLException:
--- The error occurred while applying a parameter map.
--- Check the Login.getProfileByLoginMinimal-InlineParameterMap.
--- Check the statement (query failed).
--- Cause: java.sql.SQLException: ORA-04021: timeout occurred while
waiting to lock object
at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:201)
...
at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:209)
... 89 more
Caused by: java.sql.SQLException: ORA-04021: timeout occurred while waiting to lock object 

at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)


CAUSE
The archiver process received an error while trying to archive a redo log. 

If the problem is not resolved soon, the database will stop executing transactions. The most likely cause of this message is the destination device is out of space to store the redo log file. 

 

For more information, please refer to #1585531:
What does the "ORA-00257: archiver error. Connect internal only, until
freed." error mean?
http://www-01.ibm.com/support/docview.wss?uid=swg21585531 [http://www-01.ibm.com/support/docview.wss?uid=swg21585531]



ENVIRONMENT
Connections 4.5 CR4, Oracle 11g



DIAGNOSING THE PROBLEM
The Oracle Flashback log is almost full. 

Connection to Oracle has failed due to Oracle server error: 


[1/3/17 21:59:04:653 SGT] 0000006d SystemErr R
java.sql.SQLException: ORA-00257: archiver error. Connect internal
only, until freed.
DSRA0010E: SQL State = 64000, Error Code = 257
[1/3/17 21:59:04:654 SGT] 0000006d SystemErr R at
oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)



RESOLVING THE PROBLEM
After Oracle DBA freed up flash recovery space, Connections users are able to login again.